package com.example.demo.pojo;

public class Hsk {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsk.idhsk
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    private String idhsk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsk.level
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsk.content
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    private byte[] content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsk.answer
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    private byte[] answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsk.audio
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    private byte[] audio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsk.idhsk
     *
     * @return the value of hsk.idhsk
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    public String getIdhsk() {
        return idhsk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsk.idhsk
     *
     * @param idhsk the value for hsk.idhsk
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    public void setIdhsk(String idhsk) {
        this.idhsk = idhsk == null ? null : idhsk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsk.level
     *
     * @return the value of hsk.level
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsk.level
     *
     * @param level the value for hsk.level
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsk.content
     *
     * @return the value of hsk.content
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsk.content
     *
     * @param content the value for hsk.content
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    public void setContent(byte[] content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsk.answer
     *
     * @return the value of hsk.answer
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    public byte[] getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsk.answer
     *
     * @param answer the value for hsk.answer
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    public void setAnswer(byte[] answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsk.audio
     *
     * @return the value of hsk.audio
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    public byte[] getAudio() {
        return audio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsk.audio
     *
     * @param audio the value for hsk.audio
     *
     * @mbg.generated Fri Feb 17 10:10:45 CST 2023
     */
    public void setAudio(byte[] audio) {
        this.audio = audio;
    }
}