package com.example.demo.pojo;

public class ListenBank {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listen_bank.id
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listen_bank.title
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listen_bank.picture
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    private byte[] picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column listen_bank.audio
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    private byte[] audio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listen_bank.id
     *
     * @return the value of listen_bank.id
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listen_bank.id
     *
     * @param id the value for listen_bank.id
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listen_bank.title
     *
     * @return the value of listen_bank.title
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listen_bank.title
     *
     * @param title the value for listen_bank.title
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listen_bank.picture
     *
     * @return the value of listen_bank.picture
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    public byte[] getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listen_bank.picture
     *
     * @param picture the value for listen_bank.picture
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column listen_bank.audio
     *
     * @return the value of listen_bank.audio
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    public byte[] getAudio() {
        return audio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column listen_bank.audio
     *
     * @param audio the value for listen_bank.audio
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    public void setAudio(byte[] audio) {
        this.audio = audio;
    }
}