package com.example.demo.dao;

import com.example.demo.pojo.ListeningQuestion;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ListeningQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_question
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    @Delete({
        "delete from listening_question",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_question
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    @Insert({
        "insert into listening_question (id, type, ",
        "content, option1, ",
        "option2, option3, ",
        "option4, audio_id, ",
        "answer)",
        "values (#{id,jdbcType=INTEGER}, #{type,jdbcType=INTEGER}, ",
        "#{content,jdbcType=VARCHAR}, #{option1,jdbcType=VARCHAR}, ",
        "#{option2,jdbcType=VARCHAR}, #{option3,jdbcType=VARCHAR}, ",
        "#{option4,jdbcType=VARCHAR}, #{audio_id,jdbcType=INTEGER}, ",
        "#{answer,jdbcType=VARCHAR})"
    })
    int insert(ListeningQuestion row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_question
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    @Select({
        "select",
        "id, type, content, option1, option2, option3, option4, audio_id, answer",
        "from listening_question",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="option1", property="option1", jdbcType=JdbcType.VARCHAR),
        @Result(column="option2", property="option2", jdbcType=JdbcType.VARCHAR),
        @Result(column="option3", property="option3", jdbcType=JdbcType.VARCHAR),
        @Result(column="option4", property="option4", jdbcType=JdbcType.VARCHAR),
        @Result(column="audio_id", property="audio_id", jdbcType=JdbcType.INTEGER),
        @Result(column="answer", property="answer", jdbcType=JdbcType.VARCHAR)
    })
    ListeningQuestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_question
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    @Select({
        "select",
        "id, type, content, option1, option2, option3, option4, audio_id, answer",
        "from listening_question",
        "order by age desc,username asc"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="option1", property="option1", jdbcType=JdbcType.VARCHAR),
        @Result(column="option2", property="option2", jdbcType=JdbcType.VARCHAR),
        @Result(column="option3", property="option3", jdbcType=JdbcType.VARCHAR),
        @Result(column="option4", property="option4", jdbcType=JdbcType.VARCHAR),
        @Result(column="audio_id", property="audio_id", jdbcType=JdbcType.INTEGER),
        @Result(column="answer", property="answer", jdbcType=JdbcType.VARCHAR)
    })
    List<ListeningQuestion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listening_question
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    @Update({
        "update listening_question",
        "set type = #{type,jdbcType=INTEGER},",
          "content = #{content,jdbcType=VARCHAR},",
          "option1 = #{option1,jdbcType=VARCHAR},",
          "option2 = #{option2,jdbcType=VARCHAR},",
          "option3 = #{option3,jdbcType=VARCHAR},",
          "option4 = #{option4,jdbcType=VARCHAR},",
          "audio_id = #{audio_id,jdbcType=INTEGER},",
          "answer = #{answer,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ListeningQuestion row);
}