package com.example.demo.dao;

import com.example.demo.pojo.ListenBank;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ListenBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listen_bank
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    @Delete({
        "delete from listen_bank",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listen_bank
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    @Insert({
        "insert into listen_bank (id, title, ",
        "picture, audio)",
        "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{picture,jdbcType=LONGVARBINARY}, #{audio,jdbcType=LONGVARBINARY})"
    })
    int insert(ListenBank row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listen_bank
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    @Select({
        "select",
        "id, title, picture, audio",
        "from listen_bank",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="picture", property="picture", jdbcType=JdbcType.LONGVARBINARY),
        @Result(column="audio", property="audio", jdbcType=JdbcType.LONGVARBINARY)
    })
    ListenBank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listen_bank
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    @Select({
        "select",
        "id, title, picture, audio",
        "from listen_bank",
        "order by age desc,username asc"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="picture", property="picture", jdbcType=JdbcType.LONGVARBINARY),
        @Result(column="audio", property="audio", jdbcType=JdbcType.LONGVARBINARY)
    })
    List<ListenBank> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listen_bank
     *
     * @mbg.generated Tue Feb 21 10:44:36 CST 2023
     */
    @Update({
        "update listen_bank",
        "set title = #{title,jdbcType=VARCHAR},",
          "picture = #{picture,jdbcType=LONGVARBINARY},",
          "audio = #{audio,jdbcType=LONGVARBINARY}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ListenBank row);
}