package com.example.demo.dao;

import com.example.demo.pojo.PictureBank;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface PictureBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_bank
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    @Delete({
        "delete from picture_bank",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_bank
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    @Insert({
        "insert into picture_bank (id, type, ",
        "picture_name, picture_content)",
        "values (#{id,jdbcType=INTEGER}, #{type,jdbcType=INTEGER}, ",
        "#{picture_name,jdbcType=VARCHAR}, #{picture_content,jdbcType=LONGVARBINARY})"
    })
    int insert(PictureBank row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_bank
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    @Select({
        "select",
        "id, type, picture_name, picture_content",
        "from picture_bank",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="picture_name", property="picture_name", jdbcType=JdbcType.VARCHAR),
        @Result(column="picture_content", property="picture_content", jdbcType=JdbcType.LONGVARBINARY)
    })
    PictureBank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_bank
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    @Select({
        "select",
        "id, type, picture_name, picture_content",
        "from picture_bank",
        "order by age desc,username asc"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="picture_name", property="picture_name", jdbcType=JdbcType.VARCHAR),
        @Result(column="picture_content", property="picture_content", jdbcType=JdbcType.LONGVARBINARY)
    })
    List<PictureBank> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_bank
     *
     * @mbg.generated Mon Jan 16 11:24:31 CST 2023
     */
    @Update({
        "update picture_bank",
        "set type = #{type,jdbcType=INTEGER},",
          "picture_name = #{picture_name,jdbcType=VARCHAR},",
          "picture_content = #{picture_content,jdbcType=LONGVARBINARY}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PictureBank row);
}