package com.example.demo.dao;

import com.example.demo.pojo.Word;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface WordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    @Insert({
            "insert into word (idword, content, ",
            "level)",
            "values (#{idword,jdbcType=INTEGER}, #{content,jdbcType=VARCHAR}, ",
            "#{level,jdbcType=VARCHAR})"
    })
    int insert(Word row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word
     *
     * @mbg.generated Fri Mar 03 10:12:53 CST 2023
     */
    @Select({
            "select",
            "idword, content, level",
            "from word",
            "order by age desc,username asc"
    })
    @Results({
            @Result(column = "idword", property = "idword", jdbcType = JdbcType.INTEGER),
            @Result(column = "content", property = "content", jdbcType = JdbcType.VARCHAR),
            @Result(column = "level", property = "level", jdbcType = JdbcType.VARCHAR)
    })
    List<Word> selectAll();

    @Select({
            "select",
            "idword, content, level",
            "from word",
            "where level = #{level,jdbcType=VARCHAR}",
            "limit #{position,jdbcType=INTEGER},10"
    })
    @Results({
            @Result(column = "idword", property = "idword", jdbcType = JdbcType.INTEGER),
            @Result(column = "content", property = "content", jdbcType = JdbcType.VARCHAR),
            @Result(column = "level", property = "level", jdbcType = JdbcType.VARCHAR)
    })
    List<Word> selectWordsByLevel(String level, int position);
}